language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]] ; then pip install argparse ; fi

script: ./setconf.py --test
